# Generated by Django 6.1.1 on 2026-09-10 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_app', '0004_alter_products_subcategory_alter_review_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='avito_app.products'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_image',
            field=models.ImageField(upload_to='review_images/'),
        ),
    ]
