# Generated by Django 6.1.1 on 2026-09-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_app', '0005_alter_review_product_alter_review_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
    ]
